### ISSUE TITLE
Automatic crafting is broken.

### ISSUE THREAD

**Issue by Acheron4171** [mb243/THBL#74] opened 2017-07-24 18:45 UTC
Automatic crafting using the crafting book is broken. You click on a recipe, the mats go into the crafting table and immediately back into your inventory without making anything.

**Comment by mb243** [comment] 2017-07-24 21:16
This isn't a complete issue report. Can you please:

Provide information about your game client.

- Are you running the vanillla (official) version of the game, or a third-party launcher?
- If you are running a third-party launcher which includes mods, please provide the mods that you are running.
- If you are running a third-party launcher, does the issue also occur when running the official version?
You can download the official game launcher from [this link](https://minecraft.net/en-us/download/)
- If the issue does occur with the official game client, have you reinstalled it to see if this fixes the issue?
You can find instructions for reinstalling the game client in [this guide](http://minecraft.gamepedia.com/Tutorials/Minecraft_help_FAQ#Reinstalling_Minecraft).

Describe the issue as best as you can.

- Did any error messages appear? If so, please provide the exact text.

Provide the XYZ or block coordinates you were at as closely as possible when the issue occured.

This can be invaluable when troubleshooting map-specific issues such as corrupt entities or bad chunks. You can view your coordinates from the debug screen. More information about the debug screen and getting your coordinates can be found [here](http://minecraft.gamepedia.com/Debug_screen).

Provide the date and time of the issue in UTC.

This can help locate relevant messages in the server's log.
You can convert your local time zone to UTC [here](https://time.is/UTC).

**Comment by Acheron4171** [comment] 2017-07-25 04:31
Forgive me. Try 0428, the 25th UTC. I used two different machines, both with vanilla MC. Also, issue occurs everywhere but coords are 261x62x7561 facing west, northwest.

**Comment by mb243** [comment] 2017-07-25 19:24
There's nothing relevant in the logs around this time and I'm unable to reproduce it. If you start a single player world on your local computer, do you have the same issue?

Does the issue still occur today?

**Comment by Acheron4171** [comment] 2017-07-26 03:11
Issue still occurs and only on THBL as far as I can tell.

**Comment by mb243** [comment] 2017-07-27 14:19
Is anyone else seeing this as well? What item are you attempting to craft while doing this?

**Comment by Acheron4171** [comment] 2017-07-27 17:32
So far, it has occurred with everything I've tried to craft that way. To date that is: Stone items and Glass items.

**Comment by mb243** [comment] 2017-07-30 18:11
I still haven't been able to reproduce this. Have you tried with a fresh install of Minecraft? Is anyone else seeing this?

**Comment by mb243** [comment] 2017-09-11 19:47
Closing this for lack of information. Please re-open if you're still seeing issues.

**Closed by mb243** 2017-09-11 19:47 UTC
Labels: bug
